server:
  port: 8081

spring:
  application:
    name: service-consumer-feign

feign:
  hystrix:
    enabled: true

#  在被监控的服务上添加暴露点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        #include: '*'   #'*'代表开放所有端点。